-- Generated columns and expression DEFAULT edge cases

-- GENERATED ALWAYS AS STORED — requires full table rewrite on ADD COLUMN
ALTER TABLE products
    ADD COLUMN price_with_tax NUMERIC(14,2)
    GENERATED ALWAYS AS (price * 1.1) STORED;

-- Safe: GENERATED ALWAYS AS IDENTITY (no rewrite — it's just a sequence)
CREATE TABLE orders (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL DEFAULT 1
);

-- Safe: GENERATED BY DEFAULT AS IDENTITY
CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT
);

-- ADD COLUMN with expression DEFAULT containing subquery
-- (subquery in DEFAULT is invalid SQL but let's test parser robustness)
-- Skipping as it would be a SQL error at runtime

-- ADD COLUMN with type SERIAL (creates implicit sequence)
-- This is safe in CREATE TABLE but unusual in ALTER TABLE
ALTER TABLE products ADD COLUMN sort_order SERIAL;

-- ADD COLUMN UNIQUE constraint inline (creates unique index, validates all rows)
ALTER TABLE products ADD COLUMN barcode VARCHAR(50) UNIQUE;

-- Safe: constant DEFAULT with cast
ALTER TABLE orders ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'pending'::VARCHAR;
ALTER TABLE orders ADD COLUMN metadata JSONB DEFAULT '{}'::JSONB;
