import { HistoryEntry } from "./history";

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function generateDashboard(history: HistoryEntry[]): string {
  if (history.length === 0) {
    return `<!DOCTYPE html><html><body><h1>No scan history found.</h1>
<p>Run <code>migrasafe check &lt;path&gt; --save-history</code> to start tracking scans.</p></body></html>`;
  }

  const recent = [...history].reverse().slice(0, 30);
  const totalScans = history.length;
  const safeScans = history.filter((e) => e.safe).length;
  const criticalTotal = history.reduce((s, e) => s + e.criticalCount, 0);
  const highTotal = history.reduce((s, e) => s + e.highCount, 0);
  const avgRisk = Math.round(history.reduce((s, e) => s + e.riskScore, 0) / history.length);

  // Trend chart data (last 30 scans)
  const chartLabels = JSON.stringify(recent.map((e) => e.timestamp.slice(0, 10)));
  const chartScores = JSON.stringify(recent.map((e) => e.riskScore));
  const chartIssues = JSON.stringify(recent.map((e) => e.totalIssues));

  const tableRows = recent.map((e) => {
    const statusColor = e.safe ? "#2f9e44" : "#c92a2a";
    const statusText = e.safe ? "✔ SAFE" : "✖ UNSAFE";
    const levelColor = e.riskLevel === "CRITICAL" ? "#c92a2a" : e.riskLevel === "HIGH" ? "#e67700" : e.riskLevel === "MEDIUM" ? "#d9770a" : "#2f9e44";
    return `<tr>
      <td>${esc(e.timestamp.replace("T", " ").slice(0, 19))}</td>
      <td>${esc(e.target)}</td>
      <td style="color:${statusColor};font-weight:700">${statusText}</td>
      <td>${e.totalIssues} (${e.criticalCount}C / ${e.highCount}H / ${e.mediumCount}M)</td>
      <td style="color:${levelColor};font-weight:700">${e.riskScore}/100 ${e.riskLevel}</td>
      <td>${e.files}</td>
    </tr>`;
  }).join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>migrasafe Dashboard</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js"></script>
<style>
  body{font-family:system-ui,sans-serif;margin:0;padding:24px;background:#f8f9fa;color:#212529}
  h1{font-size:1.5rem;margin:0 0 20px}
  .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:16px;margin-bottom:24px}
  .card{background:#fff;border:1px solid #dee2e6;border-radius:8px;padding:20px}
  .card h2{margin:0 0 4px;font-size:0.75rem;text-transform:uppercase;letter-spacing:.06em;color:#868e96}
  .card .value{font-size:2rem;font-weight:700;line-height:1}
  .chart-card{background:#fff;border:1px solid #dee2e6;border-radius:8px;padding:20px;margin-bottom:24px}
  .chart-card h2{margin:0 0 12px;font-size:1rem}
  table{width:100%;border-collapse:collapse;background:#fff;border-radius:8px;overflow:hidden;border:1px solid #dee2e6;font-size:0.85rem}
  th{background:#e9ecef;padding:10px 12px;text-align:left;font-size:0.75rem;text-transform:uppercase;letter-spacing:.04em}
  td{padding:9px 12px;border-bottom:1px solid #f1f3f5}
  tr:last-child td{border-bottom:none}
  .footer{margin-top:24px;font-size:0.75rem;color:#868e96}
</style>
</head>
<body>
<h1>migrasafe Dashboard</h1>

<div class="grid">
  <div class="card"><h2>Total scans</h2><div class="value">${totalScans}</div></div>
  <div class="card"><h2>Safe scans</h2><div class="value" style="color:#2f9e44">${safeScans}</div></div>
  <div class="card"><h2>CRITICAL issues</h2><div class="value" style="color:#c92a2a">${criticalTotal}</div></div>
  <div class="card"><h2>HIGH issues</h2><div class="value" style="color:#e67700">${highTotal}</div></div>
  <div class="card"><h2>Avg risk score</h2><div class="value">${avgRisk}/100</div></div>
</div>

<div class="chart-card">
  <h2>Risk Score Trend (last ${recent.length} scans)</h2>
  <canvas id="riskChart" height="80"></canvas>
</div>

<div class="chart-card">
  <h2>Issue Count Trend (last ${recent.length} scans)</h2>
  <canvas id="issueChart" height="80"></canvas>
</div>

<h2 style="margin:0 0 12px;font-size:1rem">Recent Scans</h2>
<table>
  <thead><tr><th>Time</th><th>Target</th><th>Status</th><th>Issues</th><th>Risk</th><th>Files</th></tr></thead>
  <tbody>${tableRows}</tbody>
</table>

<div class="footer">Generated by <a href="https://github.com/febrifelis/migrasafe">migrasafe</a> · ${new Date().toISOString()}</div>

<script>
const labels = ${chartLabels};
const scores = ${chartScores};
const issues = ${chartIssues};
const commonOpts = { responsive: true, plugins: { legend: { display: false } }, scales: { y: { beginAtZero: true } } };

new Chart(document.getElementById('riskChart'), {
  type: 'line',
  data: { labels, datasets: [{ label: 'Risk Score', data: scores, fill: true, borderColor: '#c92a2a', backgroundColor: 'rgba(201,42,42,0.1)', tension: 0.3 }] },
  options: { ...commonOpts, scales: { y: { beginAtZero: true, max: 100 } } }
});
new Chart(document.getElementById('issueChart'), {
  type: 'bar',
  data: { labels, datasets: [{ label: 'Issues', data: issues, backgroundColor: '#4dabf7' }] },
  options: commonOpts
});
</script>
</body>
</html>`;
}
