-- Final wave: system-level risky operations

-- CRITICAL: DROP TABLE
DROP TABLE IF EXISTS legacy_employees;
DROP TABLE old_payroll CASCADE;

-- CRITICAL: TRUNCATE
TRUNCATE TABLE tmp_import_employees;
TRUNCATE TABLE employees CASCADE;

-- CRITICAL: UPDATE without WHERE
UPDATE employees SET grade = 'B1';

-- CRITICAL: DELETE without WHERE
DELETE FROM employees;

-- HIGH: ALTER SYSTEM SET
ALTER SYSTEM SET max_connections = 300;
ALTER SYSTEM SET shared_buffers = '4GB';

-- MEDIUM: ALTER SYSTEM RESET
ALTER SYSTEM RESET max_connections;
ALTER SYSTEM RESET ALL;

-- CRITICAL: DROP DATABASE
DROP DATABASE IF EXISTS old_hr_db;

-- CRITICAL: DROP SCHEMA CASCADE
DROP SCHEMA IF EXISTS legacy_hr CASCADE;

-- HIGH: DROP VIEW
DROP VIEW IF EXISTS employee_summary;
DROP MATERIALIZED VIEW employee_stats_mv;

-- HIGH: DROP FUNCTION
DROP FUNCTION IF EXISTS calculate_bonus(BIGINT, NUMERIC);

-- HIGH: DROP TRIGGER
DROP TRIGGER IF EXISTS trg_salary_audit ON employees;

-- HIGH: ALTER TABLE SET TABLESPACE
ALTER TABLE employees SET TABLESPACE fast_nvme;

-- HIGH: ALTER SEQUENCE RESTART
ALTER SEQUENCE employees_id_seq RESTART WITH 1;

-- HIGH: ALTER SEQUENCE CYCLE
ALTER SEQUENCE employees_id_seq CYCLE;

-- HIGH: ALTER SCHEMA RENAME
ALTER SCHEMA old_hr RENAME TO deprecated_hr;

-- HIGH: ALTER TYPE RENAME
ALTER TYPE employee_grade RENAME TO staff_grade;

-- HIGH: ALTER TYPE RENAME VALUE
ALTER TYPE employee_status RENAME VALUE 'PROBATION' TO 'ON_TRIAL';

-- MEDIUM: ALTER TYPE ADD VALUE
ALTER TYPE employee_status ADD VALUE 'SUSPENDED';

-- MEDIUM: ALTER EXTENSION UPDATE
ALTER EXTENSION pg_stat_statements UPDATE TO '1.10';

-- MEDIUM: CREATE OR REPLACE VIEW
CREATE OR REPLACE VIEW active_employees AS
    SELECT id, employee_code, salary FROM employees WHERE is_active = TRUE;

-- MEDIUM: CREATE OR REPLACE FUNCTION
CREATE OR REPLACE FUNCTION get_headcount() RETURNS BIGINT AS $$
    SELECT COUNT(*) FROM employees WHERE is_active = TRUE;
$$ LANGUAGE sql;

-- MEDIUM: ATTACH PARTITION (brief lock)
ALTER TABLE payroll ATTACH PARTITION payroll_2024
    FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');

-- MEDIUM: DETACH PARTITION CONCURRENTLY
ALTER TABLE payroll DETACH PARTITION payroll_2022 CONCURRENTLY;

-- HIGH: DETACH PARTITION (no CONCURRENTLY)
ALTER TABLE payroll DETACH PARTITION payroll_2021;
