-- Stress test: partition, sequence, rename operations

-- MEDIUM: ATTACH PARTITION (brief lock)
ALTER TABLE orders ATTACH PARTITION orders_2024
    FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');

-- MEDIUM: DETACH PARTITION CONCURRENTLY
ALTER TABLE orders DETACH PARTITION orders_2022 CONCURRENTLY;

-- HIGH: DETACH PARTITION without CONCURRENTLY
ALTER TABLE orders DETACH PARTITION orders_2021;

-- HIGH: ALTER SEQUENCE RESTART
ALTER SEQUENCE orders_id_seq RESTART WITH 1;
ALTER SEQUENCE orders_id_seq RESTART;

-- HIGH: ALTER SEQUENCE CYCLE
ALTER SEQUENCE orders_id_seq CYCLE;

-- HIGH: ALTER TABLE SET TABLESPACE
ALTER TABLE orders SET TABLESPACE fast_nvme;

-- HIGH: RENAME TABLE
ALTER TABLE orders RENAME TO sales_orders;

-- HIGH: RENAME COLUMN
ALTER TABLE orders RENAME COLUMN ref TO order_ref;

-- HIGH: RENAME SCHEMA
ALTER SCHEMA public RENAME TO app;

-- HIGH: RENAME TYPE
ALTER TYPE order_status RENAME TO order_state;

-- HIGH: RENAME TYPE VALUE
ALTER TYPE order_status RENAME VALUE 'PENDING' TO 'QUEUED';

-- MEDIUM: ALTER TYPE ADD VALUE
ALTER TYPE order_status ADD VALUE 'PARTIALLY_PAID' AFTER 'PAID';

-- MEDIUM: ALTER EXTENSION UPDATE
ALTER EXTENSION pg_trgm UPDATE TO '1.6';

-- MEDIUM: CREATE OR REPLACE VIEW
CREATE OR REPLACE VIEW recent_orders AS
    SELECT * FROM orders WHERE created_at > NOW() - INTERVAL '30 days';

-- MEDIUM: CREATE OR REPLACE FUNCTION
CREATE OR REPLACE FUNCTION count_orders() RETURNS BIGINT AS $$
    SELECT COUNT(*) FROM orders;
$$ LANGUAGE sql;

-- HIGH: DROP TRIGGER
DROP TRIGGER IF EXISTS trg_orders_audit ON orders;

-- HIGH: DROP FUNCTION
DROP FUNCTION IF EXISTS old_calculate_tax(NUMERIC);

-- HIGH: DROP VIEW
DROP VIEW IF EXISTS legacy_order_report;

-- HIGH: DROP MATERIALIZED VIEW
DROP MATERIALIZED VIEW IF EXISTS order_daily_stats;

-- CRITICAL: DROP TABLE
DROP TABLE IF EXISTS legacy_orders CASCADE;

-- CRITICAL: TRUNCATE
TRUNCATE TABLE orders_staging;

-- CRITICAL: UPDATE without WHERE
UPDATE orders SET status = 'reviewed';

-- CRITICAL: DELETE without WHERE
DELETE FROM orders_temp;

-- HIGH: VACUUM FULL
VACUUM FULL orders;

-- HIGH: CLUSTER
CLUSTER orders USING idx_orders_status;

-- HIGH: LOCK TABLE
LOCK TABLE orders IN ACCESS EXCLUSIVE MODE;

-- HIGH: SET lock_timeout = 0
SET lock_timeout = 0;

-- HIGH: SET statement_timeout = 0
SET statement_timeout = 0;

-- CRITICAL: ALTER SYSTEM SET
ALTER SYSTEM SET max_connections = 500;

-- MEDIUM: ALTER SYSTEM RESET
ALTER SYSTEM RESET max_connections;
